"""identity foundation

Revision ID: 848d88164016
Revises:
Create Date: 2026-07-23 22:17:24.421420
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "848d88164016"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_index(op.f("ix_tenants_status"), "tenants", ["status"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_roles_tenant_name"),
    )
    op.create_index(op.f("ix_roles_tenant_id"), "roles", ["tenant_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("authorization_version", sa.Integer(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "username", name="uq_users_tenant_username"),
    )
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_index("ix_users_tenant_status", "users", ["tenant_id", "status"], unique=False)
    op.create_table(
        "access_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=256), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("granted_role", sa.String(length=32), nullable=False),
        sa.Column("all_spaces", sa.Boolean(), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("authorization_version", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_access_keys_expires_at"), "access_keys", ["expires_at"], unique=False)
    op.create_index(op.f("ix_access_keys_prefix"), "access_keys", ["prefix"], unique=True)
    op.create_index(op.f("ix_access_keys_revoked_at"), "access_keys", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_access_keys_tenant_id"), "access_keys", ["tenant_id"], unique=False)
    op.create_index(
        "ix_access_keys_tenant_status",
        "access_keys",
        ["tenant_id", "revoked_at", "expires_at"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("subject", sa.String(length=160), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(
        "ix_audit_logs_auth_failures",
        "audit_logs",
        ["action", "outcome", "subject", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_outcome"), "audit_logs", ["outcome"], unique=False)
    op.create_index(op.f("ix_audit_logs_subject"), "audit_logs", ["subject"], unique=False)
    op.create_index(
        "ix_audit_logs_tenant_created", "audit_logs", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_tenant_id"), "audit_logs", ["tenant_id"], unique=False)
    op.create_table(
        "knowledge_spaces",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("icon", sa.String(length=48), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("health_percent", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_spaces_tenant_name"),
    )
    op.create_index(
        op.f("ix_knowledge_spaces_status"), "knowledge_spaces", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_spaces_tenant_id"), "knowledge_spaces", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_spaces_tenant_status", "knowledge_spaces", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "access_key_knowledge_space_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("access_key_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_space_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["access_key_id"], ["access_keys.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["knowledge_space_id"], ["knowledge_spaces.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "access_key_id", "knowledge_space_id", name="uq_access_key_space_grant"
        ),
    )
    op.create_index(
        op.f("ix_access_key_knowledge_space_grants_access_key_id"),
        "access_key_knowledge_space_grants",
        ["access_key_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_key_knowledge_space_grants_knowledge_space_id"),
        "access_key_knowledge_space_grants",
        ["knowledge_space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_access_key_knowledge_space_grants_tenant_id"),
        "access_key_knowledge_space_grants",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "key_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("access_key_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("authorization_version", sa.Integer(), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bound_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["access_key_id"], ["access_keys.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_key_id", name="uq_key_bindings_access_key"),
    )
    op.create_index(
        op.f("ix_key_bindings_revoked_at"), "key_bindings", ["revoked_at"], unique=False
    )
    op.create_index(op.f("ix_key_bindings_tenant_id"), "key_bindings", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_key_bindings_user_id"), "key_bindings", ["user_id"], unique=False)
    op.create_index(
        "ix_key_bindings_user_status", "key_bindings", ["user_id", "revoked_at"], unique=False
    )
    op.create_index(
        op.f("ix_key_bindings_valid_until"), "key_bindings", ["valid_until"], unique=False
    )
    op.create_table(
        "user_knowledge_space_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_space_id", sa.Uuid(), nullable=False),
        sa.Column("can_read", sa.Boolean(), nullable=False),
        sa.Column("can_write", sa.Boolean(), nullable=False),
        sa.Column("can_manage", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_space_id"], ["knowledge_spaces.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "knowledge_space_id", name="uq_user_space_grant"),
    )
    op.create_index(
        op.f("ix_user_knowledge_space_grants_knowledge_space_id"),
        "user_knowledge_space_grants",
        ["knowledge_space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_knowledge_space_grants_tenant_id"),
        "user_knowledge_space_grants",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_knowledge_space_grants_user_id"),
        "user_knowledge_space_grants",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("key_binding_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_authorization_version", sa.Integer(), nullable=False),
        sa.Column("binding_authorization_version", sa.Integer(), nullable=False),
        sa.Column("access_key_authorization_version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["key_binding_id"], ["key_bindings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_sessions_key_binding_id"), "sessions", ["key_binding_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_revoked_at"), "sessions", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_sessions_tenant_id"), "sessions", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_index(
        "ix_sessions_user_status", "sessions", ["user_id", "revoked_at", "expires_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sessions_user_status", table_name="sessions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_tenant_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_revoked_at"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_key_binding_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_user_knowledge_space_grants_user_id"), table_name="user_knowledge_space_grants"
    )
    op.drop_index(
        op.f("ix_user_knowledge_space_grants_tenant_id"), table_name="user_knowledge_space_grants"
    )
    op.drop_index(
        op.f("ix_user_knowledge_space_grants_knowledge_space_id"),
        table_name="user_knowledge_space_grants",
    )
    op.drop_table("user_knowledge_space_grants")
    op.drop_index(op.f("ix_key_bindings_valid_until"), table_name="key_bindings")
    op.drop_index("ix_key_bindings_user_status", table_name="key_bindings")
    op.drop_index(op.f("ix_key_bindings_user_id"), table_name="key_bindings")
    op.drop_index(op.f("ix_key_bindings_tenant_id"), table_name="key_bindings")
    op.drop_index(op.f("ix_key_bindings_revoked_at"), table_name="key_bindings")
    op.drop_table("key_bindings")
    op.drop_index(
        op.f("ix_access_key_knowledge_space_grants_tenant_id"),
        table_name="access_key_knowledge_space_grants",
    )
    op.drop_index(
        op.f("ix_access_key_knowledge_space_grants_knowledge_space_id"),
        table_name="access_key_knowledge_space_grants",
    )
    op.drop_index(
        op.f("ix_access_key_knowledge_space_grants_access_key_id"),
        table_name="access_key_knowledge_space_grants",
    )
    op.drop_table("access_key_knowledge_space_grants")
    op.drop_index("ix_spaces_tenant_status", table_name="knowledge_spaces")
    op.drop_index(op.f("ix_knowledge_spaces_tenant_id"), table_name="knowledge_spaces")
    op.drop_index(op.f("ix_knowledge_spaces_status"), table_name="knowledge_spaces")
    op.drop_table("knowledge_spaces")
    op.drop_index(op.f("ix_audit_logs_tenant_id"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_tenant_created", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_subject"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_outcome"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index("ix_audit_logs_auth_failures", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_access_keys_tenant_status", table_name="access_keys")
    op.drop_index(op.f("ix_access_keys_tenant_id"), table_name="access_keys")
    op.drop_index(op.f("ix_access_keys_revoked_at"), table_name="access_keys")
    op.drop_index(op.f("ix_access_keys_prefix"), table_name="access_keys")
    op.drop_index(op.f("ix_access_keys_expires_at"), table_name="access_keys")
    op.drop_table("access_keys")
    op.drop_index("ix_users_tenant_status", table_name="users")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_tenant_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_tenants_status"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
