"""knowledge ingestion foundation

Revision ID: 8f014b8f475b
Revises: 848d88164016
Create Date: 2026-07-23 23:04:32.857316
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "8f014b8f475b"
down_revision: str | Sequence[str] | None = "848d88164016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == "postgresql"
    if is_postgresql:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=48), nullable=False),
        sa.Column("model_name", sa.String(length=160), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("distance_metric", sa.String(length=24), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "fingerprint", name="uq_embedding_profiles_fingerprint"),
    )
    op.create_index(
        "ix_embedding_profiles_enabled",
        "embedding_profiles",
        ["tenant_id", "enabled"],
        unique=False,
    )
    op.create_index(
        op.f("ix_embedding_profiles_tenant_id"), "embedding_profiles", ["tenant_id"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_space_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("original_filename", sa.String(length=240), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=False),
        sa.Column("uri", sa.String(length=1024), nullable=True),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["knowledge_space_id"], ["knowledge_spaces.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "knowledge_space_id", "content_hash", "status", name="uq_sources_space_hash_status"
        ),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(op.f("ix_sources_content_hash"), "sources", ["content_hash"], unique=False)
    op.create_index(
        op.f("ix_sources_created_by_user_id"), "sources", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_sources_deleted_at"), "sources", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_sources_knowledge_space_id"), "sources", ["knowledge_space_id"], unique=False
    )
    op.create_index(op.f("ix_sources_source_type"), "sources", ["source_type"], unique=False)
    op.create_index(
        "ix_sources_space_status",
        "sources",
        ["knowledge_space_id", "status", "updated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_sources_status"), "sources", ["status"], unique=False)
    op.create_index(op.f("ix_sources_tenant_id"), "sources", ["tenant_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("raw_object_key", sa.String(length=1024), nullable=False),
        sa.Column("normalized_markdown", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "version_number", name="uq_documents_source_version"),
    )
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_index(op.f("ix_documents_is_active"), "documents", ["is_active"], unique=False)
    op.create_index(
        "ix_documents_source_active",
        "documents",
        ["source_id", "is_active", "status"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_source_id"), "documents", ["source_id"], unique=False)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.create_index(
        op.f("ix_documents_superseded_at"), "documents", ["superseded_at"], unique=False
    )
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_space_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("heading_path", sa.JSON(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=512), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["knowledge_space_id"], ["knowledge_spaces.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_chunks_document_ordinal"),
    )
    op.create_index(op.f("ix_chunks_content_hash"), "chunks", ["content_hash"], unique=False)
    op.create_index(op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False)
    op.create_index(op.f("ix_chunks_is_active"), "chunks", ["is_active"], unique=False)
    op.create_index(
        op.f("ix_chunks_knowledge_space_id"), "chunks", ["knowledge_space_id"], unique=False
    )
    op.create_index(
        "ix_chunks_retrieval_scope",
        "chunks",
        ["tenant_id", "knowledge_space_id", "is_active"],
        unique=False,
    )
    op.create_index("ix_chunks_source_active", "chunks", ["source_id", "is_active"], unique=False)
    op.create_index(op.f("ix_chunks_source_id"), "chunks", ["source_id"], unique=False)
    op.create_index(op.f("ix_chunks_tenant_id"), "chunks", ["tenant_id"], unique=False)
    if is_postgresql:
        op.execute(
            """
            ALTER TABLE chunks
            ADD COLUMN search_vector tsvector
            GENERATED ALWAYS AS (
                to_tsvector('simple', coalesce(content, ''))
            ) STORED
            """
        )
        op.execute("CREATE INDEX ix_chunks_search_vector ON chunks USING gin (search_vector)")
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_space_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["knowledge_space_id"], ["knowledge_spaces.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_correlation_id"), "ingestion_jobs", ["correlation_id"], unique=True
    )
    op.create_index(
        op.f("ix_ingestion_jobs_document_id"), "ingestion_jobs", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_jobs_knowledge_space_id"),
        "ingestion_jobs",
        ["knowledge_space_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_requested_by_user_id"),
        "ingestion_jobs",
        ["requested_by_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_ingestion_jobs_source_created",
        "ingestion_jobs",
        ["source_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_source_id"), "ingestion_jobs", ["source_id"], unique=False
    )
    op.create_index(
        "ix_ingestion_jobs_space_status",
        "ingestion_jobs",
        ["knowledge_space_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_ingestion_jobs_tenant_id"), "ingestion_jobs", ["tenant_id"], unique=False
    )
    op.create_table(
        "chunk_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("embedding_profile_id", sa.Uuid(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["chunk_id"], ["chunks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["embedding_profile_id"], ["embedding_profiles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id", "embedding_profile_id", name="uq_chunk_embedding_profile"),
    )
    op.create_index(
        op.f("ix_chunk_embeddings_chunk_id"), "chunk_embeddings", ["chunk_id"], unique=False
    )
    op.create_index(
        op.f("ix_chunk_embeddings_embedding_profile_id"),
        "chunk_embeddings",
        ["embedding_profile_id"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_embeddings_profile",
        "chunk_embeddings",
        ["embedding_profile_id", "chunk_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chunk_embeddings_tenant_id"), "chunk_embeddings", ["tenant_id"], unique=False
    )
    if is_postgresql:
        op.execute(
            """
            CREATE INDEX ix_chunk_embeddings_embedding_hnsw
            ON chunk_embeddings
            USING hnsw (embedding vector_cosine_ops)
            """
        )
    op.create_table(
        "ingestion_job_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=320), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["ingestion_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingestion_job_events_job_created",
        "ingestion_job_events",
        ["job_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_job_events_job_id"), "ingestion_job_events", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_job_events_status"), "ingestion_job_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ingestion_job_events_tenant_id"),
        "ingestion_job_events",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_chunk_embeddings_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_job_events_tenant_id"), table_name="ingestion_job_events")
    op.drop_index(op.f("ix_ingestion_job_events_status"), table_name="ingestion_job_events")
    op.drop_index(op.f("ix_ingestion_job_events_job_id"), table_name="ingestion_job_events")
    op.drop_index("ix_ingestion_job_events_job_created", table_name="ingestion_job_events")
    op.drop_table("ingestion_job_events")
    op.drop_index(op.f("ix_chunk_embeddings_tenant_id"), table_name="chunk_embeddings")
    op.drop_index("ix_chunk_embeddings_profile", table_name="chunk_embeddings")
    op.drop_index(op.f("ix_chunk_embeddings_embedding_profile_id"), table_name="chunk_embeddings")
    op.drop_index(op.f("ix_chunk_embeddings_chunk_id"), table_name="chunk_embeddings")
    op.drop_table("chunk_embeddings")
    op.drop_index(op.f("ix_ingestion_jobs_tenant_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_space_status", table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_source_id"), table_name="ingestion_jobs")
    op.drop_index("ix_ingestion_jobs_source_created", table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_requested_by_user_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_knowledge_space_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_document_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_correlation_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_chunks_tenant_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_source_id"), table_name="chunks")
    op.drop_index("ix_chunks_source_active", table_name="chunks")
    op.drop_index("ix_chunks_retrieval_scope", table_name="chunks")
    op.drop_index(op.f("ix_chunks_knowledge_space_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_is_active"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_index(op.f("ix_chunks_content_hash"), table_name="chunks")
    op.drop_table("chunks")
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_index(op.f("ix_documents_superseded_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_source_id"), table_name="documents")
    op.drop_index("ix_documents_source_active", table_name="documents")
    op.drop_index(op.f("ix_documents_is_active"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_sources_tenant_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_status"), table_name="sources")
    op.drop_index("ix_sources_space_status", table_name="sources")
    op.drop_index(op.f("ix_sources_source_type"), table_name="sources")
    op.drop_index(op.f("ix_sources_knowledge_space_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_deleted_at"), table_name="sources")
    op.drop_index(op.f("ix_sources_created_by_user_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_content_hash"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_embedding_profiles_tenant_id"), table_name="embedding_profiles")
    op.drop_index("ix_embedding_profiles_enabled", table_name="embedding_profiles")
    op.drop_table("embedding_profiles")
    # ### end Alembic commands ###
